# Generated by Django 2.2.6 on 2019-10-31 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index_citation',
            options={'verbose_name': 'Цитата на фоновом рисунке', 'verbose_name_plural': 'Цитаты на фоновых рисунках'},
        ),
        migrations.AlterModelOptions(
            name='index_page',
            options={'verbose_name': 'Фоновый рисунок', 'verbose_name_plural': 'Фоновые рисунки'},
        ),
    ]
