# Generated by Django 2.2.6 on 2019-11-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191101_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_partners', models.TextField(blank=True, max_length=2500, verbose_name='Текст сотрудничества')),
                ('img_partners', models.ImageField(blank=True, upload_to='media/home_pages', verbose_name='Картинка сотрудничества')),
            ],
            options={
                'verbose_name': 'Сотрудничество',
                'verbose_name_plural': 'Сотрудничество',
            },
        ),
    ]
