# Generated by Django 2.2.6 on 2019-11-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_home_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_BukletPapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buklet', models.FileField(blank=True, null=True, upload_to='media/buklet_%Y%m%D', verbose_name='Буклет института')),
                ('papers', models.FileField(blank=True, null=True, upload_to='media/papers_%Y%m%D', verbose_name='Сборник научных статей')),
            ],
            options={
                'verbose_name': 'Буклет и сборник научных статей',
                'verbose_name_plural': 'Буклеты и сборники научных статей',
            },
        ),
    ]
