# Generated by Django 2.2.6 on 2019-11-06 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_home_bukletpapers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home_bukletpapers',
            options={'ordering': ['-date_pub'], 'verbose_name': 'Буклет и сборник научных статей', 'verbose_name_plural': 'Буклеты и сборники научных статей'},
        ),
        migrations.AddField(
            model_name='home_bukletpapers',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home_bukletpapers',
            name='buklet',
            field=models.FileField(blank=True, null=True, upload_to='media/bukPaper/buklet_%Y%m%D', verbose_name='Буклет института'),
        ),
        migrations.AlterField(
            model_name='home_bukletpapers',
            name='papers',
            field=models.FileField(blank=True, null=True, upload_to='media/bukPaper/papers_%Y%m%D', verbose_name='Сборник научных статей'),
        ),
    ]
