# Generated by Django 2.2.6 on 2019-11-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191106_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Buklet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buklet', models.FileField(blank=True, null=True, upload_to='media/bukPaper/buklet_%Y%m%D', verbose_name='Буклет института')),
            ],
            options={
                'verbose_name': 'Буклет',
                'verbose_name_plural': 'Буклеты',
            },
        ),
        migrations.AlterModelOptions(
            name='home_bukletpapers',
            options={'ordering': ['-date_pub'], 'verbose_name': 'Cборник научных статей', 'verbose_name_plural': 'Cборники научных статей'},
        ),
    ]
