# Generated by Django 2.2.6 on 2019-11-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191106_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_bukletpapers',
            name='buklet',
        ),
    ]
