# Generated by Django 2.2.6 on 2019-11-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('body', models.TextField(blank=True, db_index=True, max_length=2500)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='media/blog')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='media/blog')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='media/blog')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
