# Generated by Django 2.2.6 on 2019-11-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress_Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №1')),
                ('header1', models.CharField(blank=True, max_length=150, verbose_name='Название достижения №1')),
                ('text1', models.TextField(blank=True, max_length=2500, verbose_name='Текст достижения №1')),
                ('img2', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №2')),
                ('header2', models.CharField(blank=True, max_length=150, verbose_name='Название достижения №2')),
                ('text2', models.TextField(blank=True, max_length=2500, verbose_name='Текст достижения №2')),
                ('img3', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №3')),
                ('header3', models.CharField(blank=True, max_length=150, verbose_name='Название достижения №3')),
                ('text3', models.TextField(blank=True, max_length=2500, verbose_name='Текст достижения №3')),
                ('img4', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №4')),
                ('header4', models.CharField(blank=True, max_length=150, verbose_name='Название достижения №4')),
                ('text4', models.TextField(blank=True, max_length=2500, verbose_name='Текст достижения №4')),
                ('img5', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №5')),
                ('header5', models.CharField(blank=True, max_length=150, verbose_name='Название достижения №5')),
                ('text5', models.TextField(blank=True, max_length=2500, verbose_name='Текст достижения №5')),
                ('img6', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №6')),
                ('header6', models.CharField(blank=True, max_length=150, verbose_name='Название достижения №6')),
                ('text6', models.TextField(blank=True, max_length=2500, verbose_name='Текст достижения №6')),
                ('img7', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №7')),
                ('header7', models.CharField(blank=True, max_length=150, verbose_name='Название достижения №7')),
                ('text7', models.TextField(blank=True, max_length=2500, verbose_name='Текст достижения №7')),
                ('img8', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №8')),
                ('header8', models.CharField(blank=True, max_length=150, verbose_name='Название достижения №8')),
                ('text8', models.TextField(blank=True, max_length=2500, verbose_name='Текст достижения №8')),
            ],
            options={
                'verbose_name': 'Достижения института',
            },
        ),
    ]
