# Generated by Django 2.2.6 on 2019-11-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress_Work1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=150, verbose_name='Название достижения')),
                ('text', models.TextField(blank=True, max_length=2500, verbose_name='Текст достижения')),
                ('img1', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №1')),
                ('img2', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №2')),
                ('img3', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №3')),
                ('img4', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №4')),
                ('img5', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №5')),
            ],
            options={
                'verbose_name': 'Достижения института №1',
                'verbose_name_plural': 'Достижения института №1',
            },
        ),
        migrations.CreateModel(
            name='Progress_Work2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=150, verbose_name='Название достижения')),
                ('text', models.TextField(blank=True, max_length=2500, verbose_name='Текст достижения')),
                ('img1', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №1')),
                ('img2', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №2')),
                ('img3', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №3')),
                ('img4', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №4')),
                ('img5', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №5')),
            ],
            options={
                'verbose_name': 'Достижения института №2',
                'verbose_name_plural': 'Достижения института №2',
            },
        ),
        migrations.CreateModel(
            name='Progress_Work3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=150, verbose_name='Название достижения')),
                ('text', models.TextField(blank=True, max_length=2500, verbose_name='Текст достижения')),
                ('img1', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №1')),
                ('img2', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №2')),
                ('img3', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №3')),
                ('img4', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №4')),
                ('img5', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Картинка достижения №5')),
            ],
            options={
                'verbose_name': 'Достижения института №3',
                'verbose_name_plural': 'Достижения института №3',
            },
        ),
        migrations.DeleteModel(
            name='Progress_Work',
        ),
    ]
