# Generated by Django 2.2.6 on 2019-11-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_auto_20191104_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress_Potencial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.CharField(blank=True, max_length=5, verbose_name='Количеств докторов')),
                ('kan', models.CharField(blank=True, max_length=5, verbose_name='Количеств кандидатов')),
            ],
            options={
                'verbose_name': 'Научный потенциал',
                'verbose_name_plural': 'Научный потенциал',
            },
        ),
    ]
