# Generated by Django 2.2.6 on 2019-11-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_progress_potencial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress_Matbase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header1', models.CharField(blank=True, max_length=150, verbose_name='Название материальной базы №1')),
                ('text1', models.TextField(blank=True, max_length=2500, verbose_name='Описание материальной базы №1')),
                ('img1_1', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Первая картинка материальной базы №1')),
                ('img1_2', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Вторая картинка материальной базы №1')),
                ('header2', models.CharField(blank=True, max_length=150, verbose_name='Название материальной базы №2')),
                ('text2', models.TextField(blank=True, max_length=2500, verbose_name='Описание материальной базы №2')),
                ('img2_1', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Первая картинка материальной базы №2')),
                ('img2_2', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Вторая картинка материальной базы №2')),
                ('header3', models.CharField(blank=True, max_length=150, verbose_name='Название материальной базы №3')),
                ('text3', models.TextField(blank=True, max_length=2500, verbose_name='Описание материальной базы №3')),
                ('img3_1', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Первая картинка материальной базы №3')),
                ('img3_2', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Вторая картинка материальной базы №3')),
                ('header4', models.CharField(blank=True, max_length=150, verbose_name='Название материальной базы №4')),
                ('text4', models.TextField(blank=True, max_length=2500, verbose_name='Описание материальной базы №4')),
                ('img4_1', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Первая картинка материальной базы №4')),
                ('img4_2', models.ImageField(blank=True, upload_to='media/progress', verbose_name='Вторая картинка материальной базы №4')),
            ],
        ),
    ]
