# Generated by Django 2.2.6 on 2019-11-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_progress_matbase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress_matbase',
            options={'verbose_name': 'Материальная база', 'verbose_name_plural': 'Материальная база'},
        ),
        migrations.AddField(
            model_name='progress_matbase',
            name='img1_3',
            field=models.ImageField(blank=True, upload_to='media/progress', verbose_name='Третья картинка материальной базы №1'),
        ),
        migrations.AddField(
            model_name='progress_matbase',
            name='img2_3',
            field=models.ImageField(blank=True, upload_to='media/progress', verbose_name='Третья картинка материальной базы №2'),
        ),
        migrations.AddField(
            model_name='progress_matbase',
            name='img3_3',
            field=models.ImageField(blank=True, upload_to='media/progress', verbose_name='Третья картинка материальной базы №3'),
        ),
        migrations.AddField(
            model_name='progress_matbase',
            name='img4_3',
            field=models.ImageField(blank=True, upload_to='media/progress', verbose_name='Третья картинка материальной базы №4'),
        ),
    ]
