# Generated by Django 2.2.6 on 2019-11-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_command',
            name='mane_com',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя и фамилия командира'),
        ),
        migrations.AddField(
            model_name='about_command',
            name='mane_first',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя и фамилия первого зама'),
        ),
        migrations.AddField(
            model_name='about_command',
            name='mane_ndu1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя и фамилия начальника НДУ-1'),
        ),
        migrations.AddField(
            model_name='about_command',
            name='mane_ndu2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя и фамилия начальника НДУ-1'),
        ),
        migrations.AddField(
            model_name='about_command',
            name='mane_nov',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя и фамилия начальника НОВ'),
        ),
        migrations.AddField(
            model_name='about_command',
            name='mane_otd01',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя и фамилия начальника 01 отдела'),
        ),
        migrations.AddField(
            model_name='about_command',
            name='mane_polit',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя и фамилия замполита'),
        ),
        migrations.AddField(
            model_name='about_command',
            name='mane_scintific',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя и фамилия зама по науке'),
        ),
    ]
