# Generated by Django 2.2.6 on 2019-11-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20191103_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_servise',
            name='img_expluat',
            field=models.ImageField(blank=True, upload_to='media/activity', verbose_name='Картинка на ИАС'),
        ),
        migrations.AlterField(
            model_name='about_servise',
            name='img_ias',
            field=models.ImageField(blank=True, upload_to='media/activity', verbose_name='Картинка на ИАС'),
        ),
        migrations.AlterField(
            model_name='about_servise',
            name='img_mod',
            field=models.ImageField(blank=True, upload_to='media/activity', verbose_name='Картинка на ИАС'),
        ),
        migrations.AlterField(
            model_name='about_servise',
            name='img_pnp',
            field=models.ImageField(blank=True, upload_to='media/activity', verbose_name='Картинка на ИАС'),
        ),
        migrations.AlterField(
            model_name='about_servise',
            name='img_rem',
            field=models.ImageField(blank=True, upload_to='media/activity', verbose_name='Картинка на ИАС'),
        ),
    ]
