# Generated by Django 2.2.6 on 2019-11-06 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
