# Generated by Django 2.2.6 on 2019-11-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_contact_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
