# Generated by Django 2.2.6 on 2019-11-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('contact_organization', models.CharField(max_length=50, verbose_name='Организация')),
                ('contact_email', models.CharField(max_length=50, verbose_name='E-mail адрес')),
                ('contact_massage', models.TextField(max_length=3000, verbose_name='Текст сообщения')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Оставленная заявка',
                'verbose_name_plural': 'Оставленные заявки',
            },
        ),
    ]
